services:
  stx-okr-frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./stx-okr-frontend/dist:/usr/share/nginx/html:ro
    restart: always

  stx-okr-server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@stx-okr-postgres:5432/postgres?schema=public
    depends_on:
      stx-okr-postgres:
        condition: service_healthy

  stx-okr-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 100

volumes:
  postgres_data:
